CREATE TABLE TBL_USUARIO(
ID INT NOT NULL AUTO_INCREMENT,
ROL VARCHAR(100),
NOMBRE VARCHAR(100),
USUARIO VARCHAR(50),
CLAVE VARCHAR(20),
ESTADO INT,
PRIMARY KEY (ID)
);

CREATE TABLE TBL_CONDUCTOR(
ID INT NOT NULL AUTO_INCREMENT,
NUM_DOCUMENTO VARCHAR(10),
NOMBRE VARCHAR(200),
PRIMARY KEY (ID)
);

CREATE TABLE TBL_VEHICULO(
ID INT NOT NULL AUTO_INCREMENT,
NUM_PLACA VARCHAR(10),
MARCA VARCHAR(200),
PRIMARY KEY (ID)
);

CREATE TABLE  TBL_DESTINO (
ID INT NOT NULL AUTO_INCREMENT,
CODIGO VARCHAR(10),
NOMBRE  VARCHAR(200),
PRIMARY KEY (ID)
);

CREATE TABLE  TBL_ENTREGA (
ID INT NOT NULL AUTO_INCREMENT,
TICKET VARCHAR(10),
FECHA DATE,
HORA VARCHAR(10),
CONDUCTOR INT,
DESTINO INT,
VEHICULO INT,
DIESEL VARCHAR(10),
CAPACIDAD VARCHAR(10),
PRIMARY KEY (ID),
INDEX IX_ENTREGA_CONDUCTOR (CONDUCTOR), FOREIGN KEY (CONDUCTOR) REFERENCES TBL_CONDUCTOR(ID) ON DELETE CASCADE,
INDEX IX_ENTREGA_DESTINO (DESTINO), FOREIGN KEY (DESTINO) REFERENCES TBL_DESTINO(ID) ON DELETE CASCADE,
INDEX IX_ENTREGA_VEHICULO (VEHICULO), FOREIGN KEY (VEHICULO) REFERENCES TBL_VEHICULO(ID) ON DELETE CASCADE
);


INSERT INTO TBL_USUARIO (ROL, NOMBRE, USUARIO, CLAVE, ESTADO) VALUES ('ROLE_ADMIN','ADMIN','ADMIN','123456',1);
INSERT INTO TBL_USUARIO (ROL, NOMBRE, USUARIO, CLAVE, ESTADO) VALUES ('ROLE_USER','ADMIN2','ADMIN2','123456',1);