CREATE TABLE TBL_USUARIO(
ID INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
ROL VARCHAR(100),
NOMBRE VARCHAR(100),
USUARIO VARCHAR(50),
CLAVE VARCHAR(20),
ESTADO INT
);

CREATE TABLE TBL_CONDUCTOR(
ID INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
NUM_DOCUMENTO VARCHAR(10),
NOMBRE VARCHAR(200)
);

CREATE TABLE TBL_VEHICULO(
ID INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
NUM_PLACA VARCHAR(10),
MARCA VARCHAR(200)
);

CREATE TABLE  TBL_DESTINO (
ID INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
CODIGO VARCHAR(10),
NOMBRE  VARCHAR(200)
);

CREATE TABLE  TBL_ENTREGA (
ID INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
TICKET VARCHAR(10),
FECHA DATE,
HORA VARCHAR(10),
CONDUCTOR INT CONSTRAINT FK_ENTREGA_CONDUCTOR FOREIGN KEY  REFERENCES TBL_CONDUCTOR(ID),
DESTINO INT CONSTRAINT FK_ENTREGA_DESTINO FOREIGN KEY  REFERENCES TBL_DESTINO(ID),
VEHICULO INT CONSTRAINT FK_ENTREGA_VEHICULO FOREIGN KEY  REFERENCES TBL_VEHICULO(ID),
DIESEL VARCHAR(10),
CAPACIDAD VARCHAR(10)
);
